spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/mydb"
    username: "user"
    password: "password"

springdoc.swagger-ui.path: "/docs-ui"

management:
  endpoints.web.exposure.include: "health,prometheus"
  endpoint.health.group:
    liveness.include: "ping,health"
    readiness.include: "postgres"
