version: '3'
services:
  solr:
    image: solr:8.10.0
    ports:
     - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command:
      - solr-precreate
      - products

volumes:
  solr-data:
