server.port: 8080

spring:
  main:
    banner-mode: "off"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/mydb"
    username: "user"
    password: "password"
  jpa.ddl-auto: "none"
  flyway:
    enabled: "true"
    url: jdbc:postgresql://localhost:5432/mydb
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

springdoc:
  swagger-ui.path: "/docs-ui"

management:
  endpoints.web.exposure.include: "health,prometheus"
  endpoint.health.group:
    liveness.include: "ping,health"
    readiness.include: "postgres"

security:
  key:
    private: "MHgCAQEEIQCf6U4hQm7A/0qllj+QU1KW7hWwKBwGQb6uua0OGXzi16AKBggqhkjOPQMBB6FEA0IABEHoGx6/lY/4rUtCE4iXIFq/R9U+tAZWELvVfYSsr2i1Wy0RZ8IclVwkMa/5+xLi2WOuTpbYi0XqfUs/EO6hXP8="
    public: "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEHoGx6/lY/4rUtCE4iXIFq/R9U+tAZWELvVfYSsr2i1Wy0RZ8IclVwkMa/5+xLi2WOuTpbYi0XqfUs/EO6hXP8="

logging.level:
  root: "INFO"
#  org.springframework.web: "INFO"
