spring.jackson.property-naming-strategy: SNAKE_CASE

solr:
  warmup-attempt:
    max: 6
    sleep: 5s
  cluster:
    zk-hosts:
      - localhost:2181
      - localhost:2182
      - localhost:2183
#    zk-chroot: /solr8
#  standalone:
#    host: localhost
#    port: 8983

logging.level.root: INFO

management:
  endpoints.web.exposure.include: "health,prometheus"
