spring.jackson.property-naming-strategy: SNAKE_CASE

solr:
  cluster:
    zk-hosts:
      - localhost:2181
      - localhost:2182
      - localhost:2182
#    zk-chroot: /solr8
#  standalone:
#    host: localhost
#    port: 8983

logging.level.root: INFO
